### PR TITLE
Make certificate request quota configurable for shoot's custom issuers

### PR DESCRIPTION
**Pull request by MartinWeindel**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Daily quotas for certificate requests can now be explicitly set for a custom issuer defined in the providerConfig of the shoot extension spec.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Certificate request quota are configurable for custom issuer defined in the providerConfig of the shoot extension spec.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Does this mean that end-users can override the quotas for their shoots even if they don't own the issuer? Isn't this undesirable?

**Comment by MartinWeindel** [comment]
It would be overridden, if the quota is not set for an issuer explicitly.
Should I remove the overwriting of the default value?

**Comment by rfranzke** [comment]
Hm, maybe I haven't understood the purpose of this PR. Can you explain the goal again?

**Comment by MartinWeindel** [comment]
The purpuse of this PR is to be able to relax the quotas for a few exotic shoots.
Currently, request quotas are not yet activated for certificates. For example we may activate the quota with a default value of 100 certificate requests per day. With the current implementation, you can run 25 requests immediately (25% burst), but then you will have to wait 6 hours (25% of a day) for the next request, as the rate limit has been reached. This should be more than enough for almost all shoot clusters. I made a statistics for the canary and live landscape in December. There was only one shoot cluster on canary with more than 25 different certificates.
Now I was thinking how to the limits can be relaxed for such an outlier if needed. 
An alternative could be to define a custom issuer with explicit `requestsPerDayQuota` set, which is also part of this PR.

**Comment by rfranzke** [comment]
I see, thanks. My concern is the following: How do you prevent end-users from helping themselves and relaxing their quotas by default so that they are not restricted by the default value configured by Gardener operators?

**Comment by MartinWeindel** [comment]
Overriding of the default quota has been removed.

**Comment by rfranzke** [comment]
@MartinWeindel I'm confused, I still see the `requestPerDay` field in the API of this extension which can be overridden by end-users in their `Shoot`, or? Am I missing something?

**Review by timuthy — APPROVED** [review]
Nothing to be addressed from my side. I went through the code and can confirm that the quota configuration can only be set for `issuers` specified in the `certConfig` (end-user config) but not for the default `issuer` specified in the `serviceConfig`.

**Comment by rfranzke** [comment]
@timuthy OK, fine with me then, thanks for checking!

**Pull request merged**
